<<<<<<< HEAD
- name: configure react instance
  hosts: _ansible_react
  become: true
  tasks: 
    - name: update packages
      yum: 
        name: "*"
        state: latest
    - name: Uninstall old versions
      yum:
        name: "{{ item }}"
        state: removed
      loop:
=======
- name: Install docker
  gather_facts: No
  any_errors_fatal: true
  hosts: _ansible_react
  become: true
  tasks:
    - name: upgrade all packages
      yum: 
        name: '*'
        state: latest
    # we may need to uninstall any existing docker files from the centos repo first.
    - name: Remove docker if installed from CentOS repo
      yum:
        name: "{{ item }}"
        state: removed
      with_items:
>>>>>>> 4707fda649deb1e7747f84db978d40ed37adb617
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine
<<<<<<< HEAD

    - name: install yum-utils
      yum:
        name: yum-utils
        state: latest
      
=======
    - name: Install yum utils
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - yum-utils
>>>>>>> 4707fda649deb1e7747f84db978d40ed37adb617
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
<<<<<<< HEAD

=======
>>>>>>> 4707fda649deb1e7747f84db978d40ed37adb617
    - name: Install Docker
      package:
        name: docker-ce
        state: latest
<<<<<<< HEAD

    - name: Install pip
      package: 
        name: python3-pip
        state: present
        
    - name: Install docker sdk
      pip:
        name: docker

    - name: add ec2-user to docker group
=======
    - name: Install pip
      package:
        name: python3-pip
        state: present
        update_cache: true
    - name: Install docker sdk
      pip:
        name: docker
    - name: Add user ec2-user to docker group
>>>>>>> 4707fda649deb1e7747f84db978d40ed37adb617
      user:
        name: ec2-user
        groups: docker
        append: yes
<<<<<<< HEAD

    - name: start docker service
      systemd:
        name: docker
        enabled: yes
        state: started

=======
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
>>>>>>> 4707fda649deb1e7747f84db978d40ed37adb617
    - name: create build directory
      file:
        path: /home/ec2-user/react
        state: directory
        owner: root
        group: root
<<<<<<< HEAD
        mode: "0755"

    - name: copy files to the react node
      copy: 
        src: /home/ec2-user/ansible/ansible-Project/react/client/
        dest: /home/ec2-user/react

    - name: copy the dockerfile
      copy: 
        src: /home/ec2-user/ansible/ansible-Project/react/Dockerfile
        dest: /home/ec2-user/react

    - name: remove container and image if exist
      shell: "docker ps -q --filter 'name=muzeyyen_react' && docker stop muzeyyen_react && docker rm -fv muzeyyen_react && docker image rm -f muzeyyencw/react || echo 'Not Found'"

    - name: build container image
      docker_image:
        name: muzeyyencw/react
=======
        mode: '0755'
    # at this point do not forget change DB_HOST env variable for postgresql node
    - name: copy files to the nodejs node
      copy:
        src: /home/ec2-user/ansible-project/todo-app-pern/client/
        dest: /home/ec2-user/react
    - name: copy the Dockerfile
      copy:
        src: /home/ec2-user/ansible-project/react/Dockerfile
        dest: /home/ec2-user/react
    - name: remove cla_react container and clacw/react image if exists
      shell: "docker ps -q --filter 'name=cla_react' && docker stop cla_react && docker rm -fv cla_react && docker image rm -f clacw/react || echo 'Not Found'"
    - name: build container image
      docker_image:
        name: clacw/react
>>>>>>> 4707fda649deb1e7747f84db978d40ed37adb617
        build:
          path: /home/ec2-user/react
        source: build
        state: present
<<<<<<< HEAD

    - name: create react docker container
      docker_container:
        name: muzeyyen_react
        image: muzeyyencw/react
        state: started
        ports:
          - "3000:3000"
      register: container_info

    - name: print the container info
      debug:
        var: container_info
=======
    - name: Launch react docker container
      docker_container:
        name: cla_react
        image: clacw/react
        state: started
        ports:
        - "3000:3000"
      register: container_info
    - name: Print the container_info
      debug:
        msg: "{{ container_info }}"
>>>>>>> 4707fda649deb1e7747f84db978d40ed37adb617
